### ISSUE TITLE
Piping assets to a destination without modification

### ISSUE THREAD

**Issue by rogerhutchings** [jonkemp/gulp-useref#82] opened 2015-01-22 17:21 UTC
I'm just getting started with streams, and I'm hitting a bit of a wall. Basically, I want to get the assets picked up in my `index.html` build blocks, and write them to a dev folder, preserving their `src` attributes. But for some reason, this doesn't output anything:

`index.html`

```
<!-- build:js(./bower_components/) libraries.js -->
<script src="lodash/lodash.js"></script>
<script src="firebase/firebase.js"></script>
<!-- endbuild -->
```

`Gulpfile.js`

```
gulp.task('pipeAssets', function () {
    return gulp.src('app/*.html')
        .pipe(useref.assets({ noconcat: true }))
        .pipe(debug())
        .pipe(gulp.dest('./output'));
});
```

I just want to do a straight copy of the files - and they're in the stream if I use `debug()` - where am I going wrong? Thanks :)

**Comment by jonkemp** [comment] 2015-01-22 18:16
Looks like useref can't find your files. Could you try changing the build block to this?

```js
<!-- build:js libraries.js -->
<script src="/bower_components/lodash/lodash.js"></script>
<script src="/bower_components/firebase/firebase.js"></script>
<!-- endbuild -->
```

**Comment by rogerhutchings** [comment] 2015-01-22 22:38
Thanks for taking a look Jon! No luck, unfortunately :( The files are apparently in the stream at `debug()`, but aren't written anywhere.

Would it be possible to construct an array of file paths from the stream, maybe, so I could use that in `gulp.src()`?

**Comment by jonkemp** [comment] 2015-01-23 18:08
If the files are in the stream, then I'm not sure how to help. It's not a `gulp-useref` issue at that point.

**Comment by amaeland** [comment] 2015-03-09 18:51
I also have the same problem as rogerhutchings, gulp-debug shows the files so they are there. However they are not copied to destination. If I omit the { noconcat: true } it does work however it will ofcourse concat the files. Are you sure it's not related to gulp-useref?

**Comment by amaeland** [comment] 2015-03-09 21:49
So I figured out how to do it, not sure if it's the best way - but it works great for my purpose at least.
Here's what I did:

```
.pipe($.useref.assets({ noconcat: true }))
        .pipe($.tap(function (file, t) {
        	var asset = file.relative;
        	asset = asset.replace(/^(\/|\.+(?!\/[^\.]))+\.+/, basePaths.src);
        	return gulp.src(asset)
        		.pipe(gulp.dest('dist'));
        }))
```

**Comment by jonkemp** [comment] 2015-11-03 14:35
Closing.

**Closed by jonkemp** 2015-11-03 14:35 UTC

**Comment by palmerj** [comment] 2017-04-18 05:55
I'm having the same issue as stated in the original ticket. I think this issue should be reopened regardless of @amaeland hack.

**Comment by palmerj** [comment] 2017-04-18 06:20
In my case the issue is because the **base** path is not the same **path** base directory. e.g:

cwd:   ~/Documents/Development/website
base:  ~/Documents/Development/website/src/html/pages
path:  ~/Documents/Development/website/src/vendor/bootstrap/dist/css/bootstrap.css

Then after gulp.dest tries to copy the file (e.g `gulp.dest('dist/')` it results in:

cwd:   ~/Documents/Development/website
base:  ~/Documents/Development/website/dist
path:  ~/Documents/Development/vendor/bootstrap/dist/css/bootstrap.css

The files are actually being copied - just in a directory outside of my main `~/Documents/Development/website` folder and I didn't notice this at first

**Comment by palmerj** [comment] 2017-04-18 07:29
Having a little tap function like @amaeland also worked for me:

```js
// Ccreate output HTML pages from templates then
// concat & minify scripts and css
gulp.task('html', ['jshint', 'sass'], () => {
    return gulp.src('src/html/pages/**/*.hbs')
        .pipe(plumber())
        .pipe(handlebars({}, {
            ignorePartials: true,
            batch: ['src/html/partials']
        }))
        .pipe(rename({
            extname: '.html'
        }))
        .pipe(useref({ noconcat: development() }))
        .pipe(tap(function(file, t) {
            file.base = 'src';
        }))
        .pipe(gulpif('*.js', production(uglify())))
        .pipe(gulpif('*.css', production(cleanCss())))
        .pipe(gulp.dest('dist/'))
        .pipe(browserSync.stream());
});
```

**Comment by jonkemp** [comment] 2017-04-18 15:12
@palmerj Is this the same issue you are having or not?

https://github.com/jonkemp/gulp-useref/issues/208

**Comment by joshbernfeld** [comment] 2020-03-05 00:57
Thank you @palmerj !
