### ISSUE TITLE
Useref 3.0 searchPath is broken

### ISSUE THREAD

**Issue by Andrey-Pavlov** [jonkemp/gulp-useref#149] opened 2015-11-19 13:37 UTC
```
.pipe($.useref({searchPath: ['.tmp/partials', 'src', '.tmp/serve']}))

Error: File not found with singular glob: /home/xxx/xxx/{.tmp/partials,src,.tmp/bower_components/angular-toastr/dist/angular-toastr.css
```
But it works if 
```
.pipe($.useref({searchPath: ['.tmp', 'src', '.']}))
```

**Comment by jonkemp** [comment] 2015-11-19 14:23
This should be fixed now in 3.0.1. Please try that and let me know.

**Comment by Andrey-Pavlov** [comment] 2015-11-19 20:13
Thank you. Fixed.

**Closed** 2015-11-19 22:06 UTC

**Comment by agustin107** [comment] 2016-05-18 22:38
I have the same issue, because I'm working on project of webapp-generator, and when I try the command `gulp`, throw this error:

`/var/www/Github/ppfa_html/node_modules/gulp-useref/node_modules/vinyl-fs/lib/src/index.js:32
    throw new Error('Invalid glob argument: ' + glob);
    ^

Error: Invalid glob argument: 
    at Object.src (/var/www/Github/ppfa_html/node_modules/gulp-useref/node_modules/vinyl-fs/lib/src/index.js:32:11)
    at DestroyableTransform.module.exports.addAssetsToStream (/var/www/Github/ppfa_html/node_modules/gulp-useref/lib/streamManager.js:85:23)
    at /var/www/Github/ppfa_html/node_modules/gulp-useref/lib/streamManager.js:142:47
    at Array.forEach (native)
    at DestroyableTransform.module.exports.processAssets (/var/www/Github/ppfa_html/node_modules/gulp-useref/lib/streamManager.js:133:19)
    at DestroyableTransform.module.exports.processFilesAndAssets (/var/www/Github/ppfa_html/node_modules/gulp-useref/lib/streamManager.js:172:39)
    at /var/www/Github/ppfa_html/node_modules/gulp-useref/lib/streamManager.js:182:47
    at Stream.<anonymous> (/var/www/Github/ppfa_html/node_modules/event-stream/index.js:306:20)
    at _end (/var/www/Github/ppfa_html/node_modules/through/index.js:65:9)
    at Stream.stream.end (/var/www/Github/ppfa_html/node_modules/through/index.js:74:5)`

**Comment by jonkemp** [comment] 2016-05-20 14:20
@agustin107 Please try to be as detailed as possible. What is your environment? What steps will reproduce the issue? What browser(s) and OS experience the problem? All these details will help people to fix any potential bugs. Thanks!

**Comment by ryo-ogata** [comment] 2020-03-17 08:25
@jonkemp @agustin107 I have same ploblems.

gulpfile.js
```
function html() {
  return src('app/*.html')
    .pipe($.debug({title: 'htmlFiles:'}))
    .pipe($.useref({searchPath: ['.tmp', 'app', '.']}))
    .pipe($.if(/\.js$/, $.uglify({compress: {drop_console: true}})))
    .pipe($.if(/\.css$/, $.postcss([cssnano({safe: true, autoprefixer: false})])))
    .pipe($.if(/\.html$/, $.htmlmin({
      collapseWhitespace: true,
      minifyCSS: true,
      minifyJS: {compress: {drop_console: true}},
      processConditionalComments: true,
      removeComments: true,
      removeEmptyAttributes: true,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true
    })))
    .pipe(dest('dist'));
}
```

console
```
air:corp-html-gulp nity$ npm run build

> @ build /Users/nity/Documents/workspace/ours/corp-html-gulp
> cross-env NODE_ENV=production gulp

[17:19:58] Using gulpfile ~/Documents/workspace/ours/corp-html-gulp/gulpfile.js
[17:19:58] Starting 'default'...
[17:19:58] Starting 'clean'...
[17:19:58] Finished 'clean' after 26 ms
[17:19:58] Starting 'lint'...
[17:19:58] Starting 'images'...
[17:19:58] Starting 'fonts'...
[17:19:58] Starting 'extras'...
[17:20:00] Starting 'styles'...
[17:20:00] Starting 'scripts'...
[17:20:00] Starting 'modernizr'...
[17:20:01] Finished 'fonts' after 3.39 s
[17:20:02] Finished 'modernizr' after 1.37 s
[17:20:02] Finished 'lint' after 3.87 s
[17:20:02] Finished 'styles' after 1.39 s
[17:20:05] Finished 'scripts' after 4.44 s
[17:20:05] Starting 'html'...
[17:20:06] htmlFiles: app/index.html
[17:20:06] 'html' errored after 1.13 s
[17:20:06] Error: Invalid glob argument:
    at Object.src (/Users/nity/Documents/workspace/ours/corp-html-gulp/node_modules/vinyl-fs/lib/src/index.js:20:11)
    at DestroyableTransform.addAssetsToStream (/Users/nity/Documents/workspace/ours/corp-html-gulp/node_modules/gulp-useref/index.js:58:15)
    at types.forEach.type (/Users/nity/Documents/workspace/ours/corp-html-gulp/node_modules/gulp-useref/index.js:120:31)
    at Array.forEach (<anonymous>)
    at DestroyableTransform.processAssets (/Users/nity/Documents/workspace/ours/corp-html-gulp/node_modules/gulp-useref/index.js:111:11)
    at waitForAssets.pipe.es.wait (/Users/nity/Documents/workspace/ours/corp-html-gulp/node_modules/gulp-useref/index.js:174:31)
    at Stream.<anonymous> (/Users/nity/Documents/workspace/ours/corp-html-gulp/node_modules/event-stream/index.js:345:20)
    at _end (/Users/nity/Documents/workspace/ours/corp-html-gulp/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/nity/Documents/workspace/ours/corp-html-gulp/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/Users/nity/Documents/workspace/ours/corp-html-gulp/node_modules/readable-stream/lib/_stream_readable.js:577:10)
[17:20:06] 'default' errored after 8.09 s
[17:20:06] The following tasks did not complete: images, extras
[17:20:06] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `cross-env NODE_ENV=production gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nity/.npm/_logs/2020-03-17T08_20_06_457Z-debug.log
air:corp-html-gulp nity$
```

useref
```
air:corp-html-gulp nity$ npm info useref

useref@1.4.3 | MIT | deps: none | versions: 11
Parse build blocks in HTML files to replace references
https://github.com/jonkemp/useref#readme

keywords: build, blocks, build, comments, replace, scripts, link, ref

dist
.tarball: https://registry.npmjs.org/useref/-/useref-1.4.3.tgz
.shasum: 0859f9d55b205b7d5639810c34d1cdd37d254e88
.integrity: sha512-hX0qTEaDdzO3WfFl2KHQnSdaPSk8KqRaQ/nXXjBPrXzanew+12U/gm/Jt7zR978wtKMryOMXGoF0+qhYL2oseQ==
.unpackedSize: 17.2 kB

maintainers:
- jonkemp <kempdogg@gmail.com>

dist-tags:
latest: 1.4.3

published a month ago by jonkemp <kempdogg@gmail.com>
air:corp-html-gulp nity$
```
