### ISSUE TITLE
assets will not be processed, if html is in subfolder

### ISSUE THREAD

**Issue by nimo23** [jonkemp/gulp-useref#118] opened 2015-07-19 13:28 UTC
I have this in my root-directory:

* index.html
* folder-js
  * i1.js
  * i2.js
* folder-css
  * i1.css
  * i2.css
* folder-view-1
  * view-1.html
  * v1-a.js
  * v1-b.js
  * v1-a.css
  * v2-b.css

gulp-useref does process and recognize all assets of index.html (folder-js, folder-css) without errors.

**However, when processing view-1.html, gulp-useref does not process its assets.**

view-1.html contains this code **before** useref-processing:

````html
<!-- build:css v1.css -->
<link rel="stylesheet" href="v1-a.css" />
<link rel="stylesheet" href="v1-b.css" />
<!-- endbuild -->

<!-- build:js v1.js -->
<script src="v1-a.js"></script>
<script src="v1-b.js"></script>
<!-- endbuild -->
````
**view-1.html** contains this valid code **after** useref-processing:

````html
<link rel="stylesheet" href="v1.css" />
<script src="v1.js"></script>
````
**However, useref does not generate any assets of view-1.html, 
hence no v1.css or v1.js exist within folder-view-1.**

I guess, it is a bug. I am right?

**Comment by nimo23** [comment] 2015-07-19 14:09
**I am to say, it is a bug.**

I have looked at the stream with gulp-debug 
and find out, that no assets are streamed by gulp-useref, 
if html-files are placed within subfolders.

````js 
gulp.task('useref', function () {
        var assets = useref.assets();
        return gulp.src('root/folder-view1/**/*.html')
        // prints the actual file.path to console
        .pipe(debug()) 
        .pipe(assets)
        .pipe(assets.restore())
        .pipe(useref())
        .pipe(gulp.dest('dist'));
});
````

**Comment by mikeobrien** [comment] 2015-09-27 16:55
I found the same issue. The problem is it's searching for assets relative to the working directory *not* the html file. You can set the `searchPath` as follows but then you have to handle each html file individually which defeats the purpose of having the gulp plugin.

```js
var assets = useref.assets({
    searchPath: 'folder-view-1'
});
...
```

Another problem I found along the same lines is that the concatenated files are also created relative to the root as a opposed to the html file. I ended up ditching this for [gulp-usemin](https://github.com/zont/gulp-usemin), WAY better IMO:

```js
gulp.task('concat', function() {
    return gulp.src('src/**/*.html', { base: '.' })
        .pipe(usemin({ js: [ removeBom(), 'concat', ngAnnotate(), uglify(), rev() ] }))
        .pipe(gulp.dest('.'));
});
```

**Comment by nring** [comment] 2015-10-13 15:59
This might be of some use, @nimo23  It certainly helped me:
http://stackoverflow.com/questions/23350835/gulp-useref-is-throwing-error-path-must-be-a-string

**Comment by jonkemp** [comment] 2015-11-07 12:48
Maybe the latest version 2.1.0 will resolve this. There's now a base option to specify the output folder relative to the cwd.

https://github.com/jonkemp/gulp-useref#optionsbase

**Comment by jonkemp** [comment] 2015-11-19 14:41
Closing. If you want to provide feedback or test against the latest updates, we can reopen this.

**Comment by kilianc** [comment] 2015-11-30 19:13
using 3.0.3 here -- it eats up some subfolders and assets, in my case not even the .html is pushed through the pipe.

**Comment by jonkemp** [comment] 2015-11-30 20:47
Anybody want to write a test case?

**Comment by jonkemp** [comment] 2015-12-17 05:29
Change 9906172 should fix this issue.

Should be fixed in the next release.

**Closed by jonkemp** 2015-12-17 05:29 UTC
Labels: bug
