### ISSUE TITLE
Downgrading to version 2

### ISSUE THREAD

**Issue by simplyeffectiveweb** [jonkemp/gulp-useref#163] opened 2015-12-27 23:09 UTC
My question is, Is there a simple way to reinstall through the command line to version 2.0.10? 

_EDIT_: a bit of research gave me the answer, but I'd like to leave this posr cause I believe many will sympathise with it.

For anyone else new to node.js, to downgrade to 2,1.0 version (which I personally recommend if you want to manipulate assets or use rev):  

    npm install gulp-useref@2.1.0
  
**Why I wanted to downgrade** (please note I'm not asking for support or solutions on the following as downgrading to a more stable version is preferable for me)

Ver 3.0.4 is not working at all for me, giving the same error reported previously ' File not found with singular glob:'. (the error is due to useref seeming to be confused as to where assets are located as it's looking in source file folder for assets).

As much as I'd like to help, I'm not a subscriber to the 'change how a working module works' approach which is why i'm not interested in fixing ver 3 for me.

To keep interest in this module (rather than encourage people to make alternatives), it would be better to keep version 3 as a beta (until it is stable for all users and use cases are fully transferred).

For example, useref.assets made sense as a way to do 'rev' on all combined assets.  This is one use case. Now I need to use gulp if, but this is not the same as the useref assets (which are determind by the build: in HTML).  So in this respect, ver 3 is a step back.

**Comment by jonkemp** [comment] 2015-12-28 02:54
It's perfectly fine to install whichever version of the module you want and fairly simple to do. You can install a particular version via command line or set a particular version in the package.json file.

It also shouldn't be a problem to use another plugin like gulp-if, which is the way most users will use it anyway for doing minification, etc., to rev the assets. You could also use gulp-ignore to exclude html files from the stream.

I don't agree with you that it is unstable. Only 2 or 3 bug reports does not equal unstable to me. All tests pass. Documentation is up to date. I'm willing to help anyone with a problem to solve it as best I can. So there's no 'beta' label. Incrementing the major version number is the correct way to let users know that there are breaking changes in a module.

In my experience, the best way to keep interest in a module is to continue development on it and make it better, which is what I am doing. There have already been several patches in version 3.0.x as you can see.

Sorry the new version isn't working for you. I'm happy to provide you with support if you would like to create a bug report. Continuing to use the old version is fine, as long as you know it is no longer supported.

**Comment by simplyeffectiveweb** [comment] 2015-12-28 11:38
Sorry for the tone of the original message. I should have learned its better to wait before writing! I really did want to express that it is an awesome and very useful module.... but I don't think that came across! 

I am going to try to find time to test version 3 because I agree with you that in the end it's that kind of thing that helps. 

Overall I'm pretty sure there is an issue, not based on my setup. I say this because I went from a working gulp script where useref (V.2.1.0) was doing exactly as expected. Before posting, I had done / tried the following:

upgraded to V 3.0.4 (test failed due to useref.assets still in code)
changed code to remove useref.assets and added gulpif (test failed due to a long list of 'File not found with singular glob' error)
tried the same but with filter (same error as above)
removed gulpif, filter so only useref is in stream (same error as above)

When I say the same error, I mean identical error. The 'File not found' is due to useref looking for assets in the wrong place (the path shown next to the error made no sense, did not exisit and is not referenced anywhere in the code). So there was no obvious logic as to why this was happening.

My guess is, the issue is with the Build command in the HTML. Perhaps this has changed from relative to absolute, so relative paths there don't work? 

My point is, and I think it's a fair one. I took a fairly simple gulp script, changed to ver 3.0.4, adjusted the code to migrate, and it failed due to looking in the wrong place for assets. This did seem to suggest it was not stable. 

(Also, look at the number of issues in total. 11. As I'm sure you know, many more users use the module, have problems, have success, than ever post. If there are 3 people in 11 issues saying the same thing, that is quite a high percentage. Most users say nothing and just use something else if they have the option, or stop using it. And that's a shame when it is such a good module as this one).

**Comment by jonkemp** [comment] 2015-12-28 20:06
I can't speculate on what people are doing. You can see number of installs on npm and that number is going up, not down. Also, 11 issues is not a lot, but even if it were, they are not all recent, and they are not all bug reports.

In any case, I'm happy to help solve the issue. Since tests pass, this is likely a case that is not covered by tests. So I need to be able to reproduce the problem and create new test cases to create a patch if it can be solved. 

Please change the title of the issue here or create a new issue so it makes more sense. I also need you to post the stack trace, gulp task and build blocks from the html to help diagnose the problem. Thanks.

**Comment by darrrk** [comment] 2015-12-28 22:32
@simplyeffectiveweb you can try option `searchPath` for resolving this errors:
> "File not found with singular glob:"

But I agree with @simplyeffectiveweb, that 3.0.4 unstable, because I confused #162 issue and don't understand how to resolve this.

**Closed** 2016-02-04 19:05 UTC
Labels: discussion
